<a href="https://colab.research.google.com/github/DVN111/Data-Analyst-Portfolio/blob/main/Numpy_Learning_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Num.PY Learning Notes

## 1D Array

In [29]:
# belajar numpyimport numpy

import numpy as np

# create numpy array

# Vektor
vektor = np.array([1, 2, 3])
print("Vektor:")
print(vektor)

# Matriks
matriks = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatriks:")
print(matriks)

arr = np.array([1,2,3,4,5])
arr

Vektor:
[1 2 3]

Matriks:
[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5])

In [2]:
# access every pint in array
arr[0],arr[1],arr[2]

(1, 2, 3)

In [3]:
# menggunakan slicing
arr[0:]

array([1, 2, 3, 4, 5])

In [4]:
arr[1:-1]

array([2, 3, 4])

In [5]:
arr[::2]

array([1, 3, 5])

In [6]:
# tipe data array
arr.dtype
arr = np.array([1,2,3,4,5],dtype=np.float64)


In [7]:
b = np.array(['a','b','c'])
b.dtype

dtype('<U1')

## 2D Array or More

In [8]:
# array 2-3 dimensi
array2d = np.array([
#    0  1  2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
    ])

array3d = np.array([
    [[1,2,3],[1,2,3]],
    [[1,2,3],[1,2,3]]
])

print(array3d)
print('\n')
print(array2d)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# cek shape,size dan dimensi
print(array2d.shape)
print(array2d.size)
print(array2d.ndim)

(3, 3)
9
2


In [10]:
# cara select data dengan slicing pada array 2d
array2d[0,1] # baris ke 0 kolom ke 1

2

In [11]:
array2d[0:2] # baris ke 0 sampai baris ke 1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# mengganti seruh data dalam barsi 2 dimensi
array2d[2] = [10,20,30]
print(array2d)

# cara kedua
array2d[0] = 100
print(array2d)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]
[[100 100 100]
 [  4   5   6]
 [ 10  20  30]]


In [13]:
# Summary statistic
print(array2d.min())
print(array2d.max())
print(array2d.sum())
print(array2d.mean())

array2d.sum(axis=0) # jumlah kolom
array2d.sum(axis=1) # jumlah baris

4
100
375
41.666666666666664


array([300,  15,  60])

## Broadcasting and Vectorized operation

In [14]:
# arange NumPy
a = np.arange(4)
a

array([0, 1, 2, 3])

In [15]:
# operasi a
a + 5
a*10
a+=100
a

array([100, 101, 102, 103])

In [16]:
l = [1,2,3,4,5]
[i * 100 for i in l]

[100, 200, 300, 400, 500]

In [17]:
# sum list
a = np.arange(4)
b = np.array([10,10,10,10])
a+b

array([10, 11, 12, 13])

In [18]:
a = np.arange(10)
a + 20


array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

Numpy Boolean

In [21]:
# boolean numpy conditional filtering
# menggunakan operator aritmatika
a[a>2]

# menggunakan and dan or
# misalnya, kita ingin mengambil hanya bilangan genap dan yang diatas 2
a[(a>2) & (a%2==0)]
a[(a>2) | (a%2==0)]



array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a = np.arange(5)

print(a<=3)

a[a > a.mean()]

print(a.mean())

[ True  True  True  True False]
2.0


In [28]:
df = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
df
df_genap = df[df % 2 == 0] # seleksi data menggunakan booleaan
df_genap

array([2, 4, 6, 8])

In [ ]:
# aljabar linier


Notes:
- Ukuran data int dalam python 28 bytes sedangkan numpy hanya 1. sehingga itu berimplikasi terhadap performa numpy lebih baik dibandingkan menggunakan python


In [33]:
import time

In [34]:


# Measure time for list comprehension
start_time_list = time.time()
sum([x ** 2 for x in l])
end_time_list = time.time()
list_time = end_time_list - start_time_list

# Measure time for NumPy operation
start_time_np = time.time()
sum(lnp ** 2)
end_time_np = time.time()
numpy_time = end_time_np - start_time_np

list_time, numpy_time



(0.3652808666229248, 0.08641290664672852)

In [39]:

import numpy as np


# Create sample data
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 1. Descriptive Statistics
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Range:", np.ptp(data))  # Peak-to-peak (range)
print("Quantiles:", np.quantile(data, [0.25, 0.5, 0.75]))

# 2. Correlation and Covariance
data2 = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print("Correlation:", np.corrcoef(data, data2))
print("Covariance:", np.cov(data, data2))

# 3. Array Manipulation
print("Reshape:", data.reshape(2, 5))
print("Transpose:", data.reshape(2, 5).transpose())
print("Concatenate:", np.concatenate((data, data2)))

# 4. Linear Algebra
matrix = np.array([[1, 2], [3, 4]])
print("Determinant:", np.linalg.det(matrix))
print("Inverse:", np.linalg.inv(matrix))
print("Eigenvalues and Eigenvectors:", np.linalg.eig(matrix))

# 5. Sorting
print("Sorted data:", np.sort(data))

# 6. Unique Values
data_with_duplicates = np.array([1, 2, 2, 3, 3, 3, 4, 5])
print("Unique values:", np.unique(data_with_duplicates))



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Minimum: 1
Maximum: 10
Range: 9
Quantiles: [3.25 5.5  7.75]
Correlation: [[1. 1.]
 [1. 1.]]
Covariance: [[ 9.16666667 18.33333333]
 [18.33333333 36.66666667]]
Reshape: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Transpose: [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
Concatenate: [ 1  2  3  4  5  6  7  8  9 10  2  4  6  8 10 12 14 16 18 20]
Determinant: -2.0000000000000004
Inverse: [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues and Eigenvectors: EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
Sorted data: [ 1  2  3  4  5  6  7  8  9 10]
Unique values: [1 2 3 4 5]
